language: python

python:
  - 3.6.6

cache: pip

services:
  - postgresql  

before_script:
  - export SECRET_KEY='avengers'
  - export DATABASE_URL='test_db'
  - psql -c 'create database test_db;' -U postgres
  
install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - pytest --cov-report term-missing --cov=app

after_success:
- coveralls