language: python

python:
  - 3.6.6

cache: pip

services:
  - postgresql  

env:
  - DB_USER = postgres USER = postgres PASSWORD='12345'

before_script:
  - export FLASK_ENV='testing'
  - export DATABASE_URL='postgresql://postgres:12345@localhost:5432/test_db'
  - psql -c 'create database test_db;' -U postgres
  
install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - pytest --cov-report term-missing --cov=app

after_success:
- coveralls